version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: mlops-cap1
    TF_DIR: infra/terraform

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - curl -Lo terraform.zip https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip
      - unzip -o terraform.zip
      - mv terraform /usr/local/bin/terraform
      - terraform version

  pre_build:
    commands:
      - export ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - export IMAGE_TAG=${IMAGE_TAG:-$CODEBUILD_RESOLVED_SOURCE_VERSION}
      - export ECR_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  
  build:
    commands:
      - echo Running tests...
      - make install
      - make lint
      - make test

      - echo Building Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .

      - echo Tagging image...
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - docker push $ECR_URI:$IMAGE_TAG
      - cd $TF_DIR
      - terraform init -input=false
      - terraform apply -input=false -auto-approve -var="image_tag=$IMAGE_TAG"
